service: s3-lab

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: python3.8
  region: 'us-east-1'
  memorySize: 128
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:GetObject'
            - 's3:ListBucket'
          Resource:
            - arn:aws:s3:::teste-storage-random/factbook/*
            - arn:aws:s3:::teste-storage-random/factbook
            

functions:
  getObject:
    handler: handler.handler
    