service: dynamo-stream-service
provider:
  name: aws
  runtime: python3.8
  region: 'us-east-1'
  memorySize: 128
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:*'
      Resource:
        - arn:aws:dynamodb:us-east-1:*:table/*
    - Effect: 'Allow'
      Action:
        - 'firehose:*'
      Resource:
        -  arn:aws:firehose:us-east-1:*:deliverystream/*

functions:
  dynamo-processor:
    handler: lambda.handler
    events:
      - stream:
          type: dynamodb
          arn: arn:aws:dynamodb:us-east-1:924449558902:table/susep-sinistro/stream/2021-06-14T21:41:24.746
          batchSize: 1
          maximumRetryAttempts: 3
          enabled: true
          
    environment:
      kinesisName: ingest-json